//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/bpabMac/BPABPacket.msg.
//

#ifndef _BPABPACKET_M_H_
#define _BPABPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "MacPacket_m.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/mac/bpabMac/BPABPacket.msg:22</tt> by nedtool.
 * <pre>
 * enum BPABMessageType
 * {
 * 
 *     BPAB_RTB = 1;
 *     BPAB_BLACK_BURST = 2;
 *     BPAB_CTB = 3;
 *     BPAB_DATA = 4;
 * }
 * </pre>
 */
enum BPABMessageType {
    BPAB_RTB = 1,
    BPAB_BLACK_BURST = 2,
    BPAB_CTB = 3,
    BPAB_DATA = 4
};

/**
 * Enum generated from <tt>src/node/communication/mac/bpabMac/BPABPacket.msg:29</tt> by nedtool.
 * <pre>
 * enum direction
 * {
 * 
 *     EAST = 1;
 *     WEST = 2;
 *     NORTH = 3;
 *     SOUTH = 4;
 *     INTER = 5;
 * }
 * </pre>
 */
enum direction {
    EAST = 1,
    WEST = 2,
    NORTH = 3,
    SOUTH = 4,
    INTER = 5
};

/**
 * Class generated from <tt>src/node/communication/mac/bpabMac/BPABPacket.msg:37</tt> by nedtool.
 * <pre>
 * packet BPABPacket extends MacPacket
 * {
 *     int bpabType @enum(BPABMessageType);
 *     int incomingDir @enum(direction);
 *     int direction @enum(direction);
 *     double rtbSentTime;
 * 
 *     int sourceId;
 *     int destinationId;
 *     double sourceX;
 *     double sourceY;
 * 
 *     int iteration = 0;
 *     int maxIterations = 4;   // N
 *     double rangeR = 400.0;   // R
 * 
 *     double limitL;
 *     double limitU;
 * 
 *     string payload;
 * }
 * </pre>
 */
class BPABPacket : public ::MacPacket
{
  protected:
    int bpabType_var;
    int incomingDir_var;
    int direction_var;
    double rtbSentTime_var;
    int sourceId_var;
    int destinationId_var;
    double sourceX_var;
    double sourceY_var;
    int iteration_var;
    int maxIterations_var;
    double rangeR_var;
    double limitL_var;
    double limitU_var;
    opp_string payload_var;

  private:
    void copy(const BPABPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BPABPacket&);

  public:
    BPABPacket(const char *name=NULL, int kind=0);
    BPABPacket(const BPABPacket& other);
    virtual ~BPABPacket();
    BPABPacket& operator=(const BPABPacket& other);
    virtual BPABPacket *dup() const {return new BPABPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getBpabType() const;
    virtual void setBpabType(int bpabType);
    virtual int getIncomingDir() const;
    virtual void setIncomingDir(int incomingDir);
    virtual int getDirection() const;
    virtual void setDirection(int direction);
    virtual double getRtbSentTime() const;
    virtual void setRtbSentTime(double rtbSentTime);
    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);
    virtual int getDestinationId() const;
    virtual void setDestinationId(int destinationId);
    virtual double getSourceX() const;
    virtual void setSourceX(double sourceX);
    virtual double getSourceY() const;
    virtual void setSourceY(double sourceY);
    virtual int getIteration() const;
    virtual void setIteration(int iteration);
    virtual int getMaxIterations() const;
    virtual void setMaxIterations(int maxIterations);
    virtual double getRangeR() const;
    virtual void setRangeR(double rangeR);
    virtual double getLimitL() const;
    virtual void setLimitL(double limitL);
    virtual double getLimitU() const;
    virtual void setLimitU(double limitU);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, BPABPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, BPABPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _BPABPACKET_M_H_

