//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/wppMac/WppPacket.msg.
//

#ifndef _WPPPACKET_M_H_
#define _WPPPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "MacPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/mac/wppMac/WppPacket.msg:8</tt> by nedtool.
 * <pre>
 * packet WppPacket extends MacPacket
 * {
 *     int wppType = 1; // 1: DATA
 *     int originalSourceId;
 *     int senderId;
 *     int wppSeqNumber;
 *     double creationTime;
 * 
 *     // Tọa độ để tính khoảng cách (D)
 *     double sourceX;
 *     double sourceY;
 *     double senderX;
 *     double senderY;
 * 
 *     int hopCount;
 *     int ttl;
 *     string payload;
 * }
 * </pre>
 */
class WppPacket : public ::MacPacket
{
  protected:
    int wppType_var;
    int originalSourceId_var;
    int senderId_var;
    int wppSeqNumber_var;
    double creationTime_var;
    double sourceX_var;
    double sourceY_var;
    double senderX_var;
    double senderY_var;
    int hopCount_var;
    int ttl_var;
    opp_string payload_var;

  private:
    void copy(const WppPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WppPacket&);

  public:
    WppPacket(const char *name=NULL, int kind=0);
    WppPacket(const WppPacket& other);
    virtual ~WppPacket();
    WppPacket& operator=(const WppPacket& other);
    virtual WppPacket *dup() const {return new WppPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getWppType() const;
    virtual void setWppType(int wppType);
    virtual int getOriginalSourceId() const;
    virtual void setOriginalSourceId(int originalSourceId);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getWppSeqNumber() const;
    virtual void setWppSeqNumber(int wppSeqNumber);
    virtual double getCreationTime() const;
    virtual void setCreationTime(double creationTime);
    virtual double getSourceX() const;
    virtual void setSourceX(double sourceX);
    virtual double getSourceY() const;
    virtual void setSourceY(double sourceY);
    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);
    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getTtl() const;
    virtual void setTtl(int ttl);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, WppPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WppPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _WPPPACKET_M_H_

