//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/spMac/SpPacket.msg.
//

#ifndef _SPPACKET_M_H_
#define _SPPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "MacPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/mac/spMac/SpPacket.msg:7</tt> by nedtool.
 * <pre>
 * packet SpPacket extends MacPacket
 * {
 *     int spType = 1; // 1: DATA
 *     int originalSourceId;
 *     int senderId;
 *     int spSeqNumber;
 *     double creationTime;
 * 
 *     // Tọa độ phục vụ tính toán khoảng cách
 *     double sourceX;
 *     double sourceY;
 *     double senderX;
 *     double senderY;
 * 
 *     int hopCount;
 *     int ttl;
 *     string payload;
 * }
 * </pre>
 */
class SpPacket : public ::MacPacket
{
  protected:
    int spType_var;
    int originalSourceId_var;
    int senderId_var;
    int spSeqNumber_var;
    double creationTime_var;
    double sourceX_var;
    double sourceY_var;
    double senderX_var;
    double senderY_var;
    int hopCount_var;
    int ttl_var;
    opp_string payload_var;

  private:
    void copy(const SpPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SpPacket&);

  public:
    SpPacket(const char *name=NULL, int kind=0);
    SpPacket(const SpPacket& other);
    virtual ~SpPacket();
    SpPacket& operator=(const SpPacket& other);
    virtual SpPacket *dup() const {return new SpPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSpType() const;
    virtual void setSpType(int spType);
    virtual int getOriginalSourceId() const;
    virtual void setOriginalSourceId(int originalSourceId);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getSpSeqNumber() const;
    virtual void setSpSeqNumber(int spSeqNumber);
    virtual double getCreationTime() const;
    virtual void setCreationTime(double creationTime);
    virtual double getSourceX() const;
    virtual void setSourceX(double sourceX);
    virtual double getSourceY() const;
    virtual void setSourceY(double sourceY);
    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);
    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getTtl() const;
    virtual void setTtl(int ttl);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, SpPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SpPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SPPACKET_M_H_

