//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/floodingMac/FloodPacket.msg.
//

#ifndef _FLOODPACKET_M_H_
#define _FLOODPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "MacPacket_m.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/mac/floodingMac/FloodPacket.msg:11</tt> by nedtool.
 * <pre>
 * enum FloodingMessageType
 * {
 * 
 *     FLOODING_DATA = 1;
 * }
 * </pre>
 */
enum FloodingMessageType {
    FLOODING_DATA = 1
};

/**
 * Class generated from <tt>src/node/communication/mac/floodingMac/FloodPacket.msg:15</tt> by nedtool.
 * <pre>
 * packet FloodingPacket extends MacPacket
 * {
 *     int floodingType @enum(FloodingMessageType);
 * 
 *     int originalSourceId;
 *     int senderId;
 * 
 *     int floodSeqNumber;
 * 
 *     double creationTime;
 * 
 *     double sourceX;
 *     double sourceY;
 * 
 *     double senderX;
 *     double senderY;
 * 
 *     int hopCount = 0;
 * 
 *     int ttl = 20;
 * 
 *     string payload;
 * }
 * </pre>
 */
class FloodingPacket : public ::MacPacket
{
  protected:
    int floodingType_var;
    int originalSourceId_var;
    int senderId_var;
    int floodSeqNumber_var;
    double creationTime_var;
    double sourceX_var;
    double sourceY_var;
    double senderX_var;
    double senderY_var;
    int hopCount_var;
    int ttl_var;
    opp_string payload_var;

  private:
    void copy(const FloodingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FloodingPacket&);

  public:
    FloodingPacket(const char *name=NULL, int kind=0);
    FloodingPacket(const FloodingPacket& other);
    virtual ~FloodingPacket();
    FloodingPacket& operator=(const FloodingPacket& other);
    virtual FloodingPacket *dup() const {return new FloodingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getFloodingType() const;
    virtual void setFloodingType(int floodingType);
    virtual int getOriginalSourceId() const;
    virtual void setOriginalSourceId(int originalSourceId);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getFloodSeqNumber() const;
    virtual void setFloodSeqNumber(int floodSeqNumber);
    virtual double getCreationTime() const;
    virtual void setCreationTime(double creationTime);
    virtual double getSourceX() const;
    virtual void setSourceX(double sourceX);
    virtual double getSourceY() const;
    virtual void setSourceY(double sourceY);
    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);
    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getTtl() const;
    virtual void setTtl(int ttl);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, FloodingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, FloodingPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _FLOODPACKET_M_H_

